############# English navigation ##############

# Main menu in TOML format

[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Competitions"
weight = 2

[[main]]
weight = 5
name = "More"

[[main]]
parent = "More"
name = "Info"
url = "/blog/"

[[main]]
parent = "More"
name = "Team Budgets"
url = "/blog/budgets/"



[[main]]
parent = "More"
name = "Mentorship Opportunities"
url = "/blog/mentorship-opportunities"


[[main]]
name = "Team"
url = "/members/"
weight = 3

[[main]]
name = "Donate"
url = "/donations/"
weight = 4




[[main]]
parent = "Competitions"
name="All"
url = "robotics"
weight = 1

[[main]]
parent = "Competitions"
name="Vex IQ"
url = "robotics/robotics-vexiq"
weight = 2

[[main]]
parent = "Competitions"
name="FIRST Lego League"
url = "robotics/robotics-fll"
weight = 3

[[main]]
parent = "Competitions"
name="FIRST Tech Challenge"
url = "robotics/robotics-ftc"
weight = 3

[[main]]
parent = "Competitions"
name="Aerial Drones"
url = "robotics/robotics-drones"
weight = 4

[[main]]
parent = "Competitions"
name="MOEMS"
url = "math/moems"
weight = 5

[[main]]
parent = "Competitions"
name="Math Kangaroo"
url = "math/mk"
weight = 6

[[main]]
parent = "Competitions"
name="AMC 8"
url = "math/amc8"
weight = 7

[[main]]
parent = "Competitions"
name="AMC 10"
url = "math/amc10"
weight = 7

# footer menu
[[footer]]
name = "Terms of Service"
weight = 1
url = "/terms-of-service"

[[footer]]
name = "Privacy Policy"
weight = 2
url = "/privacy-policy"

[[footer_menu_quick_links]]
name = "Home"
url = "/"
weight = 1

[[footer_menu_quick_links]]
name = "Competitions"
url = "/events"
weight = 2

[[footer_menu_quick_links]]
name = "Members"
url = "/members"
weight = 3



[[footer_menu_get_started]]
name = "Donations"
url = "/donations"
weight = 1

[[footer_menu_get_started]]
name = "Mentorship Opportunities"
url = "/blog/mentorship-opportunities"
weight = 2

[[footer_menu_get_started]]
name = "Team Budgets"
url = "/blog/budgets"
weight = 3

