############# English navigation ##############

# Main menu in TOML format

[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Competitions"
url = "/events/"
weight = 2

[[main]]
weight = 5
name = "More"

[[main]]
parent = "More"
name = "Info"
url = "/blog/"

[[main]]
parent = "More"
name = "Team Budgets"
url = "/blog/budgets/"



[[main]]
parent = "More"
name = "Membership Opportunities"
url = "/blog/membership-opportunities"


[[main]]
name = "Members"
url = "/members/"
weight = 3

[[main]]
name = "Donate"
url = "/get-tickets/"
weight = 4





# footer menu
[[footer]]
name = "Terms of Service"
weight = 1
url = "/terms-of-service"

[[footer]]
name = "Privacy Policy"
weight = 2
url = "/privacy-policy"

[[footer_menu_quick_links]]
name = "Home"
url = "/"
weight = 1

[[footer_menu_quick_links]]
name = "Competitions"
url = "/events"
weight = 2

[[footer_menu_quick_links]]
name = "Members"
url = "/members"
weight = 3



[[footer_menu_get_started]]
name = "Donations"
url = "/get-tickets"
weight = 1

[[footer_menu_get_started]]
name = "Membership Opportunities"
url = "/blog/membership-opportunities"
weight = 2

[[footer_menu_get_started]]
name = "Team Budgets"
url = "/blog/budgets"
weight = 3

